### ISSUE TITLE
Make docs on sugarlabs wiki

### ISSUE THREAD

**Issue by NumbuhFour** [direkitteh/MiniGameMayhem#14]
One post on the landing page for the Math4 project and one page for the details on our project

**Comment by NumbuhFour** [comment]
I can't sign in D:

**Comment by milistisia2** [comment]
i can try to do this if it's not done yet

**Comment by milistisia2** [comment]
Managed to make a basic page on the wiki. Yay! Could use some more information and maybe a screenshot or two.
